const k = require('@kdcloudjs/kdesign');
console.log('Exports:', Object.keys(k).sort().join(', '));
console.log('Menu:', typeof k.Menu);
console.log('Menu keys:', k.Menu ? Object.keys(k.Menu).join(', ') : 'N/A');
console.log('Tabs:', typeof k.Tabs);
console.log('Tabs keys:', k.Tabs ? Object.keys(k.Tabs).join(', ') : 'N/A');
console.log('Dropdown:', typeof k.Dropdown);
console.log('Dropdown keys:', k.Dropdown ? Object.keys(k.Dropdown).join(', ') : 'N/A');
console.log('Badge:', typeof k.Badge);
console.log('Avatar:', typeof k.Avatar);
console.log('Form:', typeof k.Form);
console.log('Form keys:', k.Form ? Object.keys(k.Form).join(', ') : 'N/A');
console.log('Input:', typeof k.Input);
console.log('Input keys:', k.Input ? Object.keys(k.Input).join(', ') : 'N/A');
console.log('Select:', typeof k.Select);
console.log('Select keys:', k.Select ? Object.keys(k.Select).join(', ') : 'N/A');
console.log('Button:', typeof k.Button);
console.log('Tag:', typeof k.Tag);
console.log('Card:', typeof k.Card);
console.log('Spin:', typeof k.Spin);
console.log('Pagination:', typeof k.Pagination);
console.log('Message:', typeof k.Message);
console.log('Message keys:', k.Message ? Object.keys(k.Message).join(', ') : 'N/A');
console.log('InputNumber:', typeof k.InputNumber);
